### ISSUE TITLE
FR: Stay in Place

### ISSUE THREAD

**Issue by gerroon** [ultrasonic/ultrasonic#106]
Hi

Personally, one thing bothers me about all the s sonics players is that everytime I click on a song to play they all goto the main playing now screen. While that is nice and dandy maybe that is not what all users wants.

I really hope that the devs could add an option to keep the player where it is during song explorations.

I use US and DSUB together It think they both compliement eachother  some ways and I love both of these apps but this is one thing I hate about both of these apps as a user, not a deal breaker but just annoying if youw ill.

Thanks

**Comment by tomleb** [comment]
Has this been implemented? I also think the current behavior is annoying when adding songs to the current playlist.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
