### ISSUE TITLE
FR: Internet Radios

### ISSUE THREAD

**Issue by gerroon** [ultrasonic/ultrasonic#107]
Hi

IIt would be nice if US supports Tv/Radios listings. I use it with Airsonic, Dsub can lists these well enough.

thanks

**Comment by Tapchicoma** [comment]
Thanks for your feature request.

Currently app doesn't implement required subsonic API calls (Internet radio section), but we may add it and related UI in feature.

**Comment by varac** [comment]
Yes please :+1:

**Comment by cklabautermann** [comment]
I would love internet radio support, too.
Tanks for the wonderful app/work!

**Comment by dwilley83** [comment]
I would also like to show my support for this feature in the app.

**Comment by czadikem** [comment]
This would be very much appreciated since I have to use VLC right now to do this.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
