### ISSUE TITLE
FR: Select multiple albums

### ISSUE THREAD

**Issue by gerroon** [ultrasonic/ultrasonic#111]
Hi

At the moment one cant select multiple albums to add to playlists. It would be very helpful if the user can select multiple albums in all album views and add them to the playlist.

thanks

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
