### ISSUE TITLE
Option to sort albums by year

### ISSUE THREAD

**Issue by punk3r70** [ultrasonic/ultrasonic#192]
**New feature request:** 
I would like to see an option to sort albums by year. Currently it seems to sort based on album name.

**Comment by ogarcia** [comment]
Self annotation about this. We can use `getAlbumList2` API with `type` -> `byYear`. Is available since `1.10.1` API level.

**Comment by mixm1xmix** [comment]
Just checking this out, Great app. This is the only feature I'd like added as well. Really dislike browsing an artist with 15+ albums sorted alphabetically. Should default to chronologically :)

**Comment by punk3r70** [comment]
Sorting by folder name is another solution that will "solve" it for me. Really appreciate the work you put into the app.

**Comment by taubmann** [comment]
In addition I would like to have the option to display the year in front of the album name.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
