### ISSUE TITLE
Sort Recently Added by Added Date Descending by default

### ISSUE THREAD

**Issue by chrisacameron** [ultrasonic/ultrasonic#194]
Currently the Recently Added sorts by AlbumName alphabetically ascending. For consistency with Subsonic/Madsonic web interface, Recently Added should sort albums by Added Date descending so the most-recently added album shows first.

**Comment by ogarcia** [comment]
The Recently Added list is using same API that web view of Subsonic. They are sorted by date, newest first. If you add several albums at once, they can appear sorted alphabetically because the systems usually do the copy using that sort.

Are you checked your server? Do you have different recent list in Subsonic and in Ultrasonic?

**Comment by chrisacameron** [comment]
see screen snips from web interface vs app. The list in the app never seems to change for me.
![image](https://user-images.githubusercontent.com/10359233/38812385-c1bd249e-4151-11e8-9f9a-e6eaeb89f88f.png)
![image](https://user-images.githubusercontent.com/10359233/38812495-03d2d270-4152-11e8-9423-7da01065f7c9.png)

**Comment by chrisacameron** [comment]
The result of `GET /rest/getAlbumList.view?type=newest&size=500&offset=0&u=xxxxxx&c=UltraSonic%2520for%2520Android&f=json&v=1.7.0&p=enc:12345678900000 HTTP/1.1` on my server look to be sorted correctly (newest first). Is it being re-sorted on the app side?

**Comment by ogarcia** [comment]
Utrasonic uses this endpoint to download the Recently Added album list:
```
/rest/getAlbumList.view?type=newest&size=20&offset=0&u=USERNAME&c=Ultrasonic&f=json&v=1.8.0&p=enc:ENCPASS
```

As I see is the same that you are using. Ultrasonic don't touch the sort order.

Are you using the [latest version](https://github.com/ultrasonic/ultrasonic/releases/tag/2.4.0)? What version of Android have you?

**Comment by chrisacameron** [comment]
I have version 2.2.3 from Play Store, last updated 20-Mar-2018. Running on Android 6.0.1.

**Comment by chrisacameron** [comment]
I tried manually downloading 2.4.0 from the link you gave, but it will not install. Hesitant to uninstall/reinstall from scratch because I don't want to lose all my settings/cache

**Comment by ogarcia** [comment]
@chrisacameron yes, because the Play APK is signed with different key. But if you want latest version from Google play you can go to https://play.google.com/apps/testing/org.moire.ultrasonic and press into _Become a tester_ to have 2.4.0 from play.

This is because in Google play we are more conservative and we publish the latest version always in the beta channel.

**Comment by chrisacameron** [comment]
Thanks. I joined Beta channel & downloaded 2.4.0, but issue still exists in new version as well.

**Comment by chrisacameron** [comment]
any additional info I can provide on this?

**Comment by chrisacameron** [comment]
@ogarcia any additional info I can provide on this?

**Comment by ogarcia** [comment]
@chrisacameron if you can enter in https://gitter.im/ultrasonic/ultrasonic open a chat privately with me and provide me an unprivileged user/password to make some tests.

**Comment by chrisacameron** [comment]
issue is caused by having "Sort Songs by Disc" selected. Closing!
