### ISSUE TITLE
FR: Multiselect in Now Playing screen

### ISSUE THREAD

**Issue by weendigo** [ultrasonic/ultrasonic#209]
## Problem description

It would be nice to have a multiselect feature in the Now Playing view. 

### Steps to reproduce

My usecase:
I like to have long playlists.
Sometimes, I want to remove multiple songs from middle/end of the queue. 
That's difficult because after using context menu, the playlist view scrolls to the top.

Long-press on left side of the screen could invoke the multiselect option as in Gmail app.

## System information

 * **Ultrasonic version**: *2.5.0*
 * **Android version**: *7.0*
 * **Device info**: *Huawei Honor 8*

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
