### ISSUE TITLE
Cannot use Ultrasonic with Android Auto

### ISSUE THREAD

**Issue by uskyrt** [ultrasonic/ultrasonic#229]
## Problem description

Ultrasonic is not supported by Android Auto (or the other way 'round)

### Steps to reproduce

Try to use Ultrasonic with Android Auto

## System information

Ultrasonic version: 2.5.0
Android  * **7.1.1**: *32.4.A.1.54*
Sony Z3+

**Comment by davebiffuk** [comment]
DSub has Android Auto support and is GPL3 - I have virtually zero Java or Android programming knowledge but wonder if that might be a starting point? https://github.com/daneren2005/Subsonic

**Comment by e10kstarfire** [comment]
Any chance Android Auto support may be added? Thanks!

**Comment by SaintDubious** [comment]
I was just having a look at some of the docs [here](https://developer.android.com/training/cars/media). It looks like step 1 for this would be to correctly implement the `MediaBrowserService` which has been discussed a bit in https://github.com/ultrasonic/ultrasonic/issues/435 . Amusingly, in that thread I couldn't understand **why** we cared about external interfaces like this... and now I see why. Live and learn.

I'm not making any promises, but I'm gonna read some more on this one, see what I can figure out. @tzugen for awareness.

**Comment by tzugen** [comment]
Let me know if you need help. Personally I will focus on the database and album view stuff for the near future.

**Comment by pirahtays** [comment]
I would love to see this, this app is great   I currently have too many projects to write the code for this, but I am in process of working the bugs out of an Android Auto implementation of another app I am writing in C#.  I'm glad to help with any questions / guidance / ranting if it would be of any assistance.

**Comment by SaintDubious** [comment]
Quick update on this one: I've been making headway, but most of it has been in learning how Android Services work. Ultrasonic already has a vanilla Service [here](https://github.com/ultrasonic/ultrasonic/blob/develop/ultrasonic/src/main/kotlin/org/moire/ultrasonic/service/MediaPlayerService.kt#L50). I think to get Auto working I'll need to convert that to a MediaBrowserService (as described [here](https://developer.android.com/training/cars/media)). The issues I'm facing at the moment are just because the existing Service is a pure foreground Service, so it doesn't really play nicely when bound. So I'll work on cleaning up that aspect first.

The actual playing of music already works through the existing MediaPlayer. I managed to add the icon so you can access Ultrasonic now. The only new bit of work will be creating the new menus and support some kind of browsing and I've actually got some stubs up and running, so I don't think this will be all that hard (famous last words).

So yeah, progress is being made, but no huge success yet. Thanks for the offers of help, I'll definitely be reaching out if I get stuck.

**Comment by tzugen** [comment]
Sounds like a good idea, to extend the existing service. I tried to make it not always foreground in the notification PR, but it was too much for that PR so I scraped it. But doing so would fix #286

**Comment by tzugen** [comment]
I meant #432

**Comment by SaintDubious** [comment]
Another update: The good news is that I have an **extremely minimal** implementation working. I sorted out the issues with binding the service (found one small issue which was gumming up the works). I also created a truly minimal menu that just lets you browse by albums (and only 10 of them). And finally you can see a song list inside each album and actually play the songs. It's actually not a lot of code but given how new I am to Kotlin it took an awful lot of work.

The bad news is that there are a dizzying array of bells and whistles we can tack on to make it act like a really slick Auto application. Trying to support them all is a lot of work, and in truth I'm not even sure it's a good idea to let just one developer make all the decisions. I'd suggest that maybe a good approach is to release a basic version and then build it up based on feedback.

In any event, I'm gonna clean up what I have and submit it so that some other developers can offer early feedback, make sure I'm not off in the weeds. Then maybe we can discuss a bit more of what would be good enough for a first release. Sorry it's such slow going, I wish I had more time to work on it.

**Comment by oksijun** [comment]
If I may pitch in here... I'm a dsub/android auto user and have been following this thread with a lot of interest.

The "radio" functionality (i.e. play similar content) seems to me like it would in line with Google's focus on driving safety, I'd love to see that implemented (besides the obvious categories such as recently added, recently played, starred and so on).

Thanks for your efforts !

**Comment by SaintDubious** [comment]
Here's a bit of a document dump for anyone interested in the code: https://github.com/ultrasonic/ultrasonic/pull/512

This is not a request to actually merge, it's just a way for me to point out some of how the code works, and bring up some problems in need of solutions. Suggestions welcome.

**Comment by SaintDubious** [comment]
Quick update so that people don't think I've abandoned this project. With some help from some of the devs, I've figured out how to re-use some of the existing pieces I need to handle downloading albums. I can now also play whole albums instead of individual songs. I have both alphabetical album list and list of recently played albums. I also have a genre list, but you can't go into sub-menus yet. Rounding out the main menu is the list of Artists, but I haven't started working on that yet.

So yeah, progress, and a better idea of what the first version could look like, but nothing to show yet. Sorry for the delay, life has gotten a bit busier. It should calm down a bit in July, I hope to have something to show by then.

**Comment by SaintDubious** [comment]
Huge Thank You to @nitehu and @tzugen . This was a big piece of work and I really appreciate their time.
