### ISSUE TITLE
Playlists in Alphabetical Order

### ISSUE THREAD

**Issue by ice954pw** [ultrasonic/ultrasonic#232]
Great client, is so far exceeding Dsub. 

However, there needs to be an option to display playlists in alphabetical order, sort by title. It seems they're being sorted by when created, or parsed in the table. Tried changing it server side with no effect. Dsub has this feature. 

If anyone could correct this it would be great!

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
