### ISSUE TITLE
View album list by genre

### ISSUE THREAD

**Issue by kaysond** [ultrasonic/ultrasonic#237]
Is there a way to view a list of albums when browsing by genre? Rather than only seeing one album at a time? Is this a limitation of the API?

**Comment by lachlan-00** [comment]
@ogarcia dsub does this using the getAlbumList method with the type byGenre

DSub
```
"GET /rest/getAlbumList.view?u=user&p=PASSWORD&v=1.2.0&c=DSub&size=20&offset=0&type=byGenre&genre=00's
```
Ultrasonic
```
"GET /rest/getSongsByGenre.view?genre=%20%20Rock%20And%20Roll&count=25&offset=0&u=user&c=Ultrasonic&f=json&v=1.13.0&t=TOKEN&s=SALT
```

**Comment by haeringer** [comment]
I would like to have this, too. Would it be difficult to implement (being not a Java dev)?

Or is there any possibility already to list all albums of a particular genre?

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
