### ISSUE TITLE
Ultrasonic can't connet to Subsonic 6.1.4

### ISSUE THREAD

**Issue by djnaoki-mrn** [ultrasonic/ultrasonic#238]
## Problem description

Since the last update of subsonic (6.1.4) ultrasonic can't connect to the serveur. i tryed with others app and it's work fine.

## System information

 * **Ultrasonic version**: *2.5.0*
 * **Android version**: *8.1.0*
 * **Device info**: *OnePlus 5T*

**Comment by srayneau** [comment]
Same problème after update subsonic server to 6.1.4
Message in french "Connection échouée une erreur réseau est survenue,veuillez vérifier l'adresse du serveur ou réessayer plus tard."
-> try reconfigure new server -> ko
-> try to unistall / install the application again -> ko
-> Work with subsonic application.

**Comment by djnaoki-mrn** [comment]
hi, for add more information, when i want to connect the app to my server there are no reaching time, the app say directly that there are an issue with the network... if i shutdown the server, the app take a little time to say that there are an issue with the network.
it's as if the server directly reject the connection.
is it possible that the app use an old way of the api for the connection ? 

thanks

this is a screenshot of the message : https://ibb.co/hfwxZf

**Comment by djnaoki-mrn** [comment]
just for information ultrasonic also bug with the official demo server : http://demo.subsonic.org
usr: guest
pwd: guest

**Comment by ogarcia** [comment]
@Tapchicoma is a problem with API version. Latest version of Subsonic reports API version `1.16.1`.

Here is the error:
```
11-19 09:11:49.621 2026-2026/org.moire.ultrasonic.debug W/ServerSettingsFragment: com.fasterxml.jackson.databind.JsonMappingException: Unknown api version 1.16.1 (through reference chain: org.moire.ultrasonic.api.subsonic.response.SubsonicResponse["version"])
    com.fasterxml.jackson.databind.JsonMappingException: Unknown api version 1.16.1 (through reference chain: org.moire.ultrasonic.api.subsonic.response.SubsonicResponse["version"])
```

The Subsonic changelog says that new point added:
* REST: Added artistImageUrl to Artist and ArtistID3

The changes in was in Artist:
```xml
<xs:complexType name="Artist">
 <xs:attribute name="id" type="xs:string" use="required"/>
 <xs:attribute name="name" type="xs:string" use="required"/>
 <xs:attribute name="artistImageUrl" type="xs:string" use="optional"/>
 <!-- Added in 1.16.1 -->
 <xs:attribute name="starred" type="xs:dateTime" use="optional"/>
 <!-- Added in 1.10.1 -->
 <xs:attribute name="userRating" type="sub:UserRating" use="optional"/>
 <!-- Added in 1.13.0 -->
 <xs:attribute name="averageRating" type="sub:AverageRating" use="optional"/>
 <!-- Added in 1.13.0 -->
</xs:complexType>
```

And in ArtistID3:
```xml
<xs:complexType name="ArtistID3">
 <xs:attribute name="id" type="xs:string" use="required"/>
 <xs:attribute name="name" type="xs:string" use="required"/>
 <xs:attribute name="coverArt" type="xs:string" use="optional"/>
 <xs:attribute name="artistImageUrl" type="xs:string" use="optional"/>
 <!-- Added in 1.16.1 -->
 <xs:attribute name="albumCount" type="xs:int" use="required"/>
 <xs:attribute name="starred" type="xs:dateTime" use="optional"/>
</xs:complexType>
```

The new version of API simply add a new optional attribute.

**Comment by Tapchicoma** [comment]
Makes sense, though it is not possible for now to make an app update on play store, as app still targets api 22 :disappointed: 

Though we can still make an update to F-Droid.

**Comment by ogarcia** [comment]
@Tapchicoma is a workaround, better than nothing :sweat_smile:

**Comment by djnaoki-mrn** [comment]
yep

**Comment by weendigo** [comment]
Is there some ETA for the F-Droid update please?

**Comment by ogarcia** [comment]
@weendigo the new tag was created but we has not control over F-Droid builds. In the meantime you can download our [GitHub build](https://github.com/ultrasonic/ultrasonic/releases/download/2.6.1/ultrasonic-2.6.1.apk).

**Comment by weendigo** [comment]
@ogarcia Thanks!

**Comment by djnaoki-mrn** [comment]
Thanks you so mutch !!

**Comment by Tapchicoma** [comment]
Let's keep this bug open. App should better behave in future on such api updates.

**Comment by blinkertoon** [comment]
I've tried to install the apk but am getting 'app not installed' at the end?

**Comment by ogarcia** [comment]
@blinkertoon you must uninstall older version before install the new one. The github version cannot be installed over Google Play version or F-Droid version.

**Comment by blinkertoon** [comment]
Ok, thanks. Will try again.

**Comment by DocMarty84** [comment]
Hello!

Is there any news for a new build on Google Play?

**Comment by Tapchicoma** [comment]
Not in the nearest future. Still missing:
- either drop or support app permissions (storage)
- target api 28

**Comment by DocMarty84** [comment]
OK thanks, I'll work around it then :smile:

**Comment by ogarcia** [comment]
Related Issue: #79

**Comment by nate2014jatc** [comment]
![screenshot_20190226-113834_ultrasonic](https://user-images.githubusercontent.com/11836893/53437617-2e4d5b80-39bb-11e9-97c6-06481adf8558.png)
Hi there, I saw that 2.6.1 released with a partial fix, but I'm using 2.6.1 and I'm completely unable to connect to my server.

**Comment by deusxanime** [comment]
Also have this problem on my Android phone (Pixel 3 stock) running the Google Play Store version which looks to be currently 2.5.0, so no surprise. Hadn't really noticed since I generally just use Ultrasonic to sync my music from my Airsonic server (unRAID docker by binhex), but usually use Google Play Music for actual playback since it integrates with stuff better like Android Auto, Maps, etc. But I popped it open to grab some more files and am getting the same error as on @nate2014jatc screenshot. Waiting for fix on Play Store as I like to stick to that if at all possible! Thanks for you work!

**Comment by deusxanime** [comment]
So I am setting up a new device and since the Play Store version doesn't work I had no choice but to grab the latest apk from github (v2.6.1 appears to still be it, as linked above) and I tried using that. I'm still getting the same errors as in the screenshot above when trying to setup my server and connect - Network Error Occured...

Luckily on my old device I still had most of my music downloaded for offline use and so I could just listen to it using the Play Music app even though Ultrasonic didn't work, but on my new device now I obviously can't even get it to start up so I can download my music/playlists.

Has there been any progress on a fix? Even better a fix that can be published to the Play Store?

I'm using it with Airsonic 10.3.1-RELEASE (not entirely sure what Subsonic that is based on) running on unRAID docker container.

**Comment by deusxanime** [comment]
Interesting development...

I got the upgrade to Android 10 today on my Pixel 3 (running bone stock, no bootloader/root/rom/etc) and I was poking through apps to see if anything broke with the new OS version and came to Ultrasonic. I decided to fire it up on a whim expecting the same as above (I am running the Play Store version 2.5.0) and it gave me a warning about possibly not working due to new OS etc. An aside - my Ultrasonic is basically a new install as I deleted all of its data a couple months back in an attempt to get it work, which failed at the time of course. Since it is a clean install I've never been able to add a working server due to the above error, but I went through the process and put in the info for my Airsonic server (docker container running in unRAID, version on the about page shows "10.4.0-RELEASE – July 13, 2019"). I got the error above like normal and was about to give up and continue on but changed one thing before I did. It was failing with the above error in this thread when I used server address of http://192.168.0.10:4040/ but if I removed the trailing slash and used http://192.168.0.10:4040 it started working!

I've started setting it up again and it seems to be continuing to work. I'm able to playback songs and have pinned a playlist which downloaded all the songs in it for me. 

Don't know what the difference is or why it works in Android 10 but had stopped working in the previous Android version, but I'll take it! As far as I can see the app hasn't been updated in over a year, so doesn't seem like a new version of that being the fix, something in the OS.

**Comment by SenorSmartyPants** [comment]
I just installed Ultrasonic from Play store and can't get it to connect to the latest Airsonic. DSub connects with the same server info .

**Comment by stacyharper** [comment]
Hello there ! I got the same error message on 2.6.2 with a 0.19.0 funkwhale.
Is it normal ?

**Comment by stacyharper** [comment]
> Is it normal ?

Yeah if you don't read the manual 

> In your client configuration, please double check the “ID3” or “Browse with tags” setting is enabled.

[funkwhale manual](https://docs.funkwhale.audio/users/apps.html?highlight=android#enabling-subsonic-on-your-funkwhale-account)

**Comment by ghost** [comment]
Just to add my experience to it:
I couldnt get it running with Ultrasonic at all.
But i got it working with the Audinaut app, with additionally Switching off the Salt/Token Authentication.
