### ISSUE TITLE
Ultrasonic send p auth instead of t+s auth when using API 1.13.0

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#253]
I've added a workaround for this in Ampache but here's the issue.

By default it seems Ultrasonic supports 1.7.0 auth. I've recently added 1.13.0 support to ampache which uses token authentication.

When connecting to Ampache with ultrasonic i will sometimes get a 1.7.0 request instead of the token request which will fail to connect.

It seems to be mostly around ping and getlicense
```
"GET /rest/ping.view?u=%user%&c=Ultrasonic&f=json&v=1.7.0&p=enc:%AUTH% HTTP/1.1" 200 4064 "-" "okhttp/3.10.0"
"GET /rest/getLicense.view?u=%user%&c=Ultrasonic&f=json&v=1.13.0&p=enc:%AUTH% HTTP/1.1" 200 595 "-" "okhttp/3.10.0
```
Once it has had an error connecting it will work again but Ultrasonic should probably pick an auth method and stick with it.

I think setting auth for p or t+s based on "Enable support for LDAP users" setting would probably be an easy way to fix this.

**Comment by piti-diablotin** [comment]
I have a question/remark regarding this issue.
I recently upgraded ampache 3.XXX (don't remember) to the lastest 4 master branch and my ultrasonic did not connect anymore. Yes I have LDAP users.
I had to investigate to figure out the problem. Indeed enabling the p auth for LDAP users in ultrasonic solved the problem. 
My question is when/where the apikey should be generated for ultrasonic ? How to provide it ? Is it automatically done by the server ? 
Why this t+s auth cannot be used with LDAP since there is a sync with the sql database ?

This might be more relevant to ampache and thus @lachlan-00 why is there only one apikey in the SQL table while an apikey should be generated for each individual client, shouldn't it ?

**Comment by lachlan-00** [comment]
It's definitely not ultrasonics issue as far as apikey auth in Ampache is used.

I should document it somewhere in the wiki and if you'd like to move your question to the Ampache repo I'll work out where and make a few pictures for it. It's in the user preferences tab under "account"

The reason Ampache and subsonic differ is the way passwords are securely stored are not the same.

The apikey in Ampache was the only way I could semi privately do token auth. It's generated per-user from the interface and not generated by default as it's stored in plain text on the database.

**Comment by nitehu** [comment]
This is caused by Ultrasonic continously trying to find out what API version a server uses. It defaults to 1.7.0 when Ultrasonic starts, and then updates the version from the first response of the server (usually a Ping).

The problem is that when Ultrasonic starts, it has no means to know what version of the protocol to use to communicate with the server. One solution is that we let the user configure this, but IMHO there are enough user complaints already that they can't connect to a server, they don't need another parameter to be set correctly.

I think the better solution would be to try to auto-detect these parameters the first time Ultrasonic connects to a server (and maybe later when a related error is received). 
- It can try to connect to the server using both the T+S and the P authentication, and stick to whatever works
- It also could warn the user if a certificate is self-signed, and ask if they want to connect still (and remember the response).
This way these server related settings also could be removed - or can be disabled by an "auto-detect settings" switch, and enabled by power users for maximum flexibility.

**Comment by piti-diablotin** [comment]
This sounds fine to me. 

I think the version is specify in the request to the server right? So if 1.7 works for all the features ultrasonic has then why to change ?

Maybe a warning should be displayed if the user uses P auth and no SSL/TLS for the http request ....

**Comment by nitehu** [comment]
Ultrasonic uses features from API version 1.1 to 1.12, so it needs to know what version the server is capable of. 

Actually, if unencrypted HTTP is used, the T+S auth is not much secure than the P auth. T+S uses the obsolete MD5 hash, and also, I doubt that the servers store all the past salts to make replay attacks impossible.

**Comment by lachlan-00** [comment]
as a server. (ampache) i send the minimum server version or the maximum?

i have thought that it was maximum for server and min for client. so if my version is over 1.12 then it should be token authby dedault

shouldn't this be cached somewhere after pinging on login/test?

**Comment by nitehu** [comment]
You're absolutely right, I also think the simplest solution is that Ultrasonic should stick to one authentication method.
I'm just saying currently it tries its best to follow the version and still work (at least partially) if you upgrade/downgrade your server, and this causes the problem. 
In Ampache's case this fails so spectacularly because Ampache uses separate password and API Key for the two types of authentication... 😊

I'm too thinking on executing a mandatory connection test in the background when a new server is added, and setting the authentication properties accordingly. There shouldn't be too much users who downgrade their server everyday, and they probably can manage their Ultrasonic settings...

**Comment by lachlan-00** [comment]
> In Ampache's case this fails so spectacularly because Ampache uses separate password and API Key for the two types of authentication... 😊

What would the world be without edge cases? ;)

**Comment by piti-diablotin** [comment]
Yes I think as far as the login works when adding the server, all the other communications should work with the same auth mechanism
Thanks for the work
