### ISSUE TITLE
Feature Request: Chromecast Support and VLC inyegration

### ISSUE THREAD

**Issue by surfrock66** [ultrasonic/ultrasonic#272]
I'm looking to get off of DSub and this seems like a great option, however Chromecast support is a critical feature for me as that's how I send music to my kids' rooms.  I searched the issues and didn't see it requested, is Chromecast support on the roadmap?  

Also I see flash and MX player are the only supported video players.  Can VLC support be on the roadmap as well?

**Comment by jbmfg** [comment]
Same exact situation for me re: casting.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
