### ISSUE TITLE
Display album covers

### ISSUE THREAD

**Issue by AhatLi** [ultrasonic/ultrasonic#292]
I want each album cover to appear in front of the song name in the playlist.
If you display album covers I think it will be a better app in terms of design and functionality.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
