### ISSUE TITLE
Can't see albums on funkwhale

### ISSUE THREAD

**Issue by martinszy** [ultrasonic/ultrasonic#303]
## Problem description

Adding the servers had a problem: can't select them if they don't have a name. It shouldn't let me exit the configuration without a name. But after I figured that out I was able to listen to music.

Browsing artists works fine, but listing the albums doesn't, search doesn't work either.

This is with two different funkwhale 1.0 servers.

### Steps to reproduce

1. Install ultrasonic
2. Add a funkwhale server in the configuration and select it
3. Go to library
4. click an artist
5. "network error"

## System information

 * **Ultrasonic version**: 2.11.0
 * **Android version**: 10
 * **Device info**: Samsung

## Additional notes

Cool app :)

**Comment by nitehu** [comment]
Wow, I didn't even know Funkwhale existed! And they list Ultrasonic as their recommended Android client!
Anyways, I've checked their implementation, the problem is the following:

```
D/OkHttp: <-- 404 https://fw.neko.bar/rest/getMusicDirectory.view?id=3016&u=nitehu&c=Ultrasonic&f=json&v=1.16.0&t=***&s=*** (58ms)
    server: nginx
    date: Sun, 20 Sep 2020 05:58:15 GMT
    content-type: text/html
    content-length: 179
    vary: Cookie, Origin
    x-frame-options: DENY
    x-content-type-options: nosniff
    x-xss-protection: 1; mode=block
D/OkHttp: <!doctype html>
    <html lang="en">
    <head>
      <title>Not Found</title>
    </head>
    <body>
      <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
    </body>
    </html>
    <-- END HTTP (179-byte body)

```

It seems they don't support getMusicDirectory Subsonic API yet, so this problem doesn't seem to be Ultrasonic related.
Please also see [https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1054](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1054), according to their own GitLab, this is an open issue at Funkwhale. It seems to me Funkwhale is currently under heavy development.

**Comment by ogarcia** [comment]
Close this. Not our bug and no more info from issuer.
