### ISSUE TITLE
[Feature Request] Play directly on press

### ISSUE THREAD

**Issue by awsms** [ultrasonic/ultrasonic#320]
Is there a way to immediatly launch a song once it's pressed, instead of having to tick it, then press play in the bottom left?

**Comment by nitehu** [comment]
I think currently you can't do this.

Ultrasonic is very much playlist oriented, its main use case is to play a bunch of songs which the user ordered into a list. It is too easy to overwrite a playlist by an inadvertent touch if it starts playing the song immediately (I've done this multiple times in e.g. foobar2000, and each time I almost got a heart attack when my carefully planned (but unsaved) playlist was gone).

Maybe a "single touch enqueue in current playlist and start playing" feature can be implemented, but maybe that would be too confusing as a user experience.

**Comment by awsms** [comment]
That makes sense, I perfectly understand that point. I use my music player on the desktop the same as you do, playlist oriented. But I have a very different use on my mobile, I always want to play "that song", than "this one" etc.

>Maybe a "single touch enqueue in current playlist and start playing" feature can be implemented, but maybe that would be too confusing as a user experience.

I think it could be doable, for example adding a "play immediatly on touch" in the settings which will add the song to the current playlist, then play it immediatly, as you said.
But then the whole UI would have to be rethinked (adding a context menu on a long press for a song, or a "three dots" button at the extrme-right instead of the bookmark star of a song which will open a context menu); and keeping the exact same current UI for the "select the songs to add to the current playlist" default mode.

**Comment by awsms** [comment]
I noticed something interesting, the behaviour I'm looking for is exactly the one when you do a search, and press/long press on a song.

**Comment by kaythomas0** [comment]
I've been wondering about this too. I love Ultrasonic but this is probably the one thing that keeps me from using it over other Subsonic apps.

**Comment by reikuzan** [comment]
im new, install airsonic just 2days ago and use it with this amazing ultrasonic, this feature/option would be perfect. :) hope it will be added soon.

**Comment by ogarcia** [comment]
I think that we must change the behavior of the app to do somethink like this:
![photo_2020-11-05_11-31-25](https://user-images.githubusercontent.com/572924/98229664-79728c80-1f5a-11eb-8c75-682d013178b3.jpg)
Instead of have a checker by element of list, have the three dots menu with the options:
![photo_2020-11-05_11-31-29](https://user-images.githubusercontent.com/572924/98230050-fdc50f80-1f5a-11eb-976a-83e29947013b.jpg)

The good of this is that you can play a song directly (losing your current playlist), the bad is that you cannot select several songs to be added to playlist or downloaded.

The long press cannot be used because is now used to show full name of a song.

IMHO, I would not make this change, the lost is greater than the benefit

**Comment by kaythomas0** [comment]
I personally like that idea a lot. Being able to add multiple songs to a playlist/queue quickly is much more of a niche use case for me compared to playing directly on tap, which is how every music app on a mobile device I've ever used behaves. Though I do understand people have different use cases than me.

**Comment by ogarcia** [comment]
As this FR breaks the app philosophy cannot be implemented. Closing.

**Comment by awsms** [comment]
> As this FR breaks the app philosophy cannot be implemented. Closing.

Mh.. how exactly? even you agreed on this
