### ISSUE TITLE
TimeCheck timeout for IAudioFlinger command 41

### ISSUE THREAD

**Issue by radopas** [ultrasonic/ultrasonic#325]
Hello,

Since some time my Ultrasonic started crashing at startup. 
It is quite possible that my AOSP distro is buggy, but I've managed to avoid the crash by disabling the instantiation of EqualizerController and VisualizerController in LocalMediaPlayer by commenting the static block initializer.

Attached is the logcat crash log.
[logcat_ultrasonic.txt](https://github.com/ultrasonic/ultrasonic/files/5324148/logcat_ultrasonic.txt)

**Comment by ogarcia** [comment]
Seems a problem with your AOSP, that have a missing library:
```
2020-10-04 21:39:17.882 22476-22484/? E/EffectsFactoryConfigLoader: Could not find library in effect directories: libswdap.so
```

**Comment by radopas** [comment]
Yes, most probably this is the reason. But i also use other audio players and only ultrasonic crashes. I guess the other players don't use this library, or attach to it differently. 
Could you tell me where are used the equalizer and visualizer? Would it work if i implement a checkbox "Disable equalizer" in the settings? This way it will not crash anymore for me, and could save some resources for other users. It seems trivial to check the flag during the initialization. Is there other places where i need to put it?

**Comment by nitehu** [comment]
I think instead of (yet another) setting, this should be detected by Ultrasonic automatically, if possible. It seems it already tries to do that with `checkAvailable`, maybe those checks could be implemented correctly.

**Comment by radopas** [comment]
I can't find where in Ultrasonic are used the equalizer and visualizer, so i don't know if they have any meaning to be instantiated at all.
I have zero knowledge in Android and can't say would it be possible, but it sound to me more difficult to implement reliably. 
Today I've checked several players (VLC, Plex, Dsub, RadioDroid) and none shows the error in logcat.

**Comment by nitehu** [comment]
@radopas There should be an exception in logcat before `ExecuteOnStartedMediaPlayerService failed to get a MediaPlayerService instance!` which tells us exactly what failed where. In the newest version of Ultrasonic, there is a debug log option at the end of the settings page. Could you please try to capture a debug log for us?

**Comment by radopas** [comment]
Here you are
[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/5359795/ultrasonic.1.log)
[ultrasonic-stacktrace.txt](https://github.com/ultrasonic/ultrasonic/files/5359796/ultrasonic-stacktrace.txt)

**Comment by nitehu** [comment]
I think I see what happened here.
The root of the problem seems to be that after API28 the background services (like the MediaPlayerService) are forced to show a notification in a few seconds after they start, otherwise they're killed by the os.
According to the log creating the equalizer and the visualizer fails very slowly for you, which makes the service start timeout.

If this is the problem, initializing the equalizer and the visualizer on a new thread solves this. If these calls can be slow, it is better to offload them to a new thread from the service initialization anyways.

@radopas Unfortunately I can't test that this approach solves your problem, at least it didn't make anything worse. Would you please try to apply this patch on your version and test it for us?

[fix_equalizer.txt](https://github.com/ultrasonic/ultrasonic/files/5360682/fix_equalizer.txt)

**Comment by radopas** [comment]
@nitehu Thanks, now it doesn't crash at startup.
But still there is a lot of situations when i get freeze with black screen and delay -  when start playing songs, when rotate the screen and change orientation, even when turn on the screen from sleep.
I'm attaching a log file from today. I hope that it would help, but tell me if you need any more information 
[ultrasonic.1.log](https://github.com/ultrasonic/ultrasonic/files/5373445/ultrasonic.1.log)

**Comment by nitehu** [comment]
Thank you, it seems only the timeout was the problem. This can be emulated by adding a sleep to these functions, this way the remaining problem with the freeze can be tested further and fixed. I'll get back to you soon.
