### ISSUE TITLE
Allow adding single discs to the playlist

### ISSUE THREAD

**Issue by KingDuckZ** [ultrasonic/ultrasonic#338]
When you open an album you see all songs listed in one single view. For multi-disc albums this is confusing as sometimes I only want to play the second disc. As far as I can tell currently there is no way to do this except selecting songs one by one.
The opposite is also a problem, ie if I add the whole album to the playlist then removing songs I don't want is very tedious as you have to scroll to the song in the playlist, long-press an entry, select "remove", then the playlist resets to the top and you have to repeat the whole process. This is a separate issue, but it's just to say it's not a viable workaround.

Describe your problem here. Describe what you want to happen, and what happens
if you try to do it. If you have a stack trace or any logs, please format them using
github triple backquote notation

### Steps to reproduce

1. find an album made of 2 or more discs
2. add that to airsonic
3. find that album in ultrasonic and click on it
4. note how you see the full list of songs one after the other with no separation or anything else, not even per-disc jacket covers are respected
5. try to play just one disc, see how there is no straightforward way of doing it

## System information

 * **Ultrasonic version**: 2.15.0
 * **Android version**: LineageOS 17.1-20201022-NIGHTLY-pioneer
 * **Device info**: Sony Xperia 2

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
