### ISSUE TITLE
Add the ability to stop the download of an entire Artist

### ISSUE THREAD

**Issue by twisp007** [ultrasonic/ultrasonic#349]
## Problem description

Currently downloading for songs in the music library is done only per track or per album. If one wants to download all the songs of an artist it gets really repetitive and unnecessarily long. 

## System information

 * **Ultrasonic version**: *2.15.0*
 * **Android version**: *5.1.1*

**Comment by nitehu** [comment]
I've just noticed that if you click "Artists" in "Ultrasonic Main", then long-click an Artist in the list, and select "Download" in the popup menu, that will recursively download all the albums of the Artist... 
Isn't this the function this issue is about?

However, Ultrasonic does this silently in the background, and the user can't see nor cancel it, at least when the songs aren't currently in a playlist. So there is room for improvement of this feature...

**Comment by ogarcia** [comment]
@nitehu I completely forgot the long press behaviour in artist list, but you have reason, the only possible improvement is that you can cancel the download

**Comment by tzugen** [comment]
Closing in favour of #441
