### ISSUE TITLE
add a song to an existing playlist

### ISSUE THREAD

**Issue by AhatLi** [ultrasonic/ultrasonic#352]
**New feature request:**
I want to add a song to an existing playlist
Ultrasonic doesn't seem to have this feature
Are there any plans to add this feature?

**Comment by RomainTT** [comment]
Indeed, this feature would be nice. In the current version it is only possible to read a playlist, and while reading it some new tracks can be added to it.

Ideally, a **long press** on a song, in any view (current playlist, tracks browsing…), should show a new item **Add to playlists…**. When selecting it, a list of available playlists would show, and one *or more* can be selected.

**Comment by tigermick** [comment]
Hi,
+1
Great feature to add in ultrasonic. I'd rather to use this possibility.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
