### ISSUE TITLE
Jukebox play queue doesn't update

### ISSUE THREAD

**Issue by jambw** [ultrasonic/ultrasonic#377]
## Problem description
I've noticed that if you change the order or delete songs from the play queue whilst playing songs in jukebox mode the songs disappear from the queue but still play on the server. It seems the playlist on the server doesn't update when a change is made. When you skip to the next song, the correct one displays on the app but the removed song still plays. If you skip back and forward between songs the queue that actually plays seems to stay the same as when you first pressed "Jukebox on" despite displaying different songs in the app. 

### Steps to reproduce

Add songs to queue
Jukebox on
Start playing
Delete 2nd song in queue by swiping it away, song disappears
Press skip
2nd song plays, whilst app displays the 3rd one
Skip again
3rd song plays, whilst app displays the 4th one

If you delete a couple of songs and change the order slightly the playlist can become particularly unpredictable :-)

## System information

 * **Ultrasonic**: *2.16.0*
 * **Android version**: *10*
 * **Device info**: *Moto G7 power*

## Additional notes

Server is airsonic-advanced 11.0.0-SNAPSHOT.20200916153357

**Comment by ogarcia** [comment]
Please, check with latest beta. If still present, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
