### ISSUE TITLE
Feature: Playback Speed (audio books)

### ISSUE THREAD

**Issue by grahamPegNetwork** [ultrasonic/ultrasonic#384]
Hello, I'd like to recommend adding playback speed adjustment as an option, potentially hidden from UI until enabled in settings to reduce clutter.

Personal notes, i use airsonic for auriobooks exclusovely and have used:
Plex
DSub
Sync + Pulsar
Plexamp

Currently testing Audinaut and Ultrasonic. So far it feels like Ultrasonic is near the top in terms of UX, but seems to be lacking the one critical feature for us; playback speed.

Thanks for the consideration!

**Comment by tzugen** [comment]
This could be implemented by using `androidx.media2.MediaPlayer`

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
