### ISSUE TITLE
Add savePlayQueue on pause/resume

### ISSUE THREAD

**Issue by lachlan-00** [ultrasonic/ultrasonic#386]
Would it be possible to send savePlayQueue on pause/resume?

I didn't see an obvious option in settings.

**Comment by nitehu** [comment]
Wow I didn't even know this existed :)
Ultrasonic stores the play queue and position in a file now, but I think it would be fairly trivial to call an API instead, if so configured. Personally I like the idea to be able to store this online, as I often lose my queue because of the lots of testing.

**Comment by lachlan-00** [comment]
At least having a fall back to file on top of this should make it a bit more robust.

It's also really good on the server side to inform about the user actually doing things

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
