### ISSUE TITLE
Redesign context menu

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#388]
At this moment when you do a long click on an item in song list or album list, the first long click tries to maximize the item to show full text and second long press shows the context menu. I think that is better remove this behaviour and simply to have two lines for element title. And if the element does not fit in two lines simply finsh the second line with `...` as other players like YouTube music.

In the other hand. Maybe we can _remove_ the long press replacing the star icon with a vertical three dots icon that shows the menu when it is pressed. What do you think?

**Comment by nitehu** [comment]
Yep at first this was strange for me too, I thought it is a bug and had to check previous versions.
Also I think the (double) long press is not intuitive at all, I wouldn't find this function on the UI if I don't see it in the code. So IMHO the three dots context menu would be a way better solution, instead of or besides the stars.
I agree long lines can be finished with "...", they can also start scrolling after a time.

**Comment by tzugen** [comment]
I think a long press should show the context menu, indepedent of whether the Album has a long name or not. I did this in #437 .
Long names are shortened with a `..`. I don't think we need to implement a special feature to show to full name, if users want to see the full name, they can just select the album...

**Comment by ogarcia** [comment]
@tzugen I think that is better (for consistency and avoid long press) replace the Star icon with a vertical three dots icon that shows menu when it is pressed and add all options in this menu

**Comment by ogarcia** [comment]
The menu can be something like this, that is very very very more beautiful than a simple menu
![photo_2021-04-27_12-30-53](https://user-images.githubusercontent.com/572924/116227441-71024e00-a754-11eb-9987-f3f0fb8f5a3e.jpg)

**Comment by tzugen** [comment]
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/388
