### ISSUE TITLE
Stop After Current option request

### ISSUE THREAD

**Issue by vadiof** [ultrasonic/ultrasonic#396]
I'm an old foobar2000 user and really like it. I also like Ultrasonic though it is not perfect. One of the option that I miss on Ultrasonic is Stop After Current which makes playback stop after the current track ends. I'd really appreciate if it will be added. And I think this option could make Ultrasonic one step to the perfection.
Thanks!

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
