### ISSUE TITLE
Playback pauses without user interaction

### ISSUE THREAD

**Issue by tzugen** [ultrasonic/ultrasonic#402]
## Problem description

Suddenly playback pauses. There is a suspicious line in the logs:

```
09:12:42.979: I MediaPlayerLifecycleSupport Headset event for: null 
09:12:42.985: I LocalMediaPlayer STARTED -> PAUSED (DownloadFile (Entry(id=2399, parent=191, isDirectory=false, title=Strange Cities, album=Desire Loop, albumId=181, artist=Lori Scacco, artistId=144, track=2, year=2018, genre=Electronic, contentType=audio/mpeg, suffix=mp3, transcodedContentType=, transcodedSuffix=, coverArt=191, size=9436073, songCount=null, duration=288, bitRate=261, path=Lori Scacco - Desire Loop - 2018 (WEB - MP3 - V0)/02 Strange Cities.mp3, isVideo=false, starred=false, discNumber=-1, type=music, created=Tue Feb 26 15:14:11 GMT+01:00 2019, closeness=0, bookmarkPosition=0, userRating=null, averageRating=null))) 
```

### Steps to reproduce

Not yet sure.

## System information

 * **Ultrasonic version**:  Latest on F-Droid
 * **Android version**: Lineage 17.1

## Additional notes

Include any extra notes here. Otherwise you may remove this section.

**Comment by nitehu** [comment]
This happens when the OS sends an "ACTION_HEADSET_PLUG" event, which means that a wired headset is plugged / unplugged.
I guess you didn't unplugged any wired headsets, otherwise you wouldn't report this as an issue :)
For now it seems this is a bug in Lineage, and I'm not sure what more can we do other than adding some debug logging to see in details what is the intent Ultrasonic receives...

**Comment by tzugen** [comment]
Was probably a hardware defect (broken headphone cable)
:facepalm:
