### ISSUE TITLE
Authentication by token is not supported for LDAP users

### ISSUE THREAD

**Issue by GoaLitiuM** [ultrasonic/ultrasonic#404]
I'm getting an error "Connection failure. Authentication by token is not supported for LDAP users." even though I have not setup LDAP in the airsonic-advanced server or seen anything LDAP related settings in the Ultrasonic itself. I previously used regular airsonic server where everything worked just fine, but after switching to this new fork, I can't connect to it with Ultrasonic.

### Steps to reproduce

- Setup a new airsonic-advanced server
- Change default credentials
- Add new server in Ultrasonic with same credentials
- Hit Test Connection button

## System information

 * **Ultrasonic version**: *2.19.2*
 * **Android version**: *Android 10 (MIUI 11.0.4)*
 * **Device info**: *Xiaomi Redmi Note 9 Pro*

**Comment by nitehu** [comment]
So I've just tested Ultrasonic with airsonic-advanced. This process works for me:
- Install newest release of airsonic-advanced (10.6.0)
- Use default password admin/admin
- Add media library
- Connect with Ultrasonic using the default server settings, enter admin/admin for credentials
- It just works!

Now the tricky part is when I try to change the admin password.
- Change admin password to "password"
- Still use default server settings in Ultrasonic, enter admin/password
- Server response: Wrong username or password
- Enter admin/admin
- Connection is ok! Like the password was never changed ??? This seems to be an airsonic-advanced bug
- Switch "Force plain password authentication" on in Ultrasonic
- Enter admin/password
- Connection is OK, as it should be.

So I think I've found an airsonic bug, but I can't reproduce your problem.
"Authentication by token is not supported for LDAP users." is a string returned by airsonic-advanced, and not by Ultrasonic, so maybe the problem is in the server configuration. 
I can only add that "token" might refer to the authentication type when the "Force plain password" is off. 
Try to set it to on, and see what happens - or try to reproduce the above steps on a new airsonic-advanced install.

**Comment by tzugen** [comment]
@GoaLitiuM do you still have this problem?

**Comment by GoaLitiuM** [comment]
Sorry, I worked around the issue. I changed the credential encoder to one of the decodable ones (encrypted-AES-GCM) and Ultrasonic connects just fine. None of the non-decodable encoders work with Ultrasonic as far as I know.

**Comment by rpi-maker** [comment]
> 
> @GoaLitiuM 
> Sorry, I worked around the issue. I changed the credential encoder to one of the decodable ones (encrypted-AES-GCM) and Ultrasonic connects just fine. None of the non-decodable encoders work with Ultrasonic as far as I know.

This worked for me as well, connecting Ultrasonic Client App for Android to the Airsonic Advanced Server using a decodable credential encoder (encrypted-AES-GCM) for a limited access user.

**Comment by zoenglinghou** [comment]
I have the same issue with Nextcloud Music subsonic server. Is this a client or server issue?

**Comment by tzugen** [comment]
Nextcloud server is known to have some bugs..

**Comment by nitehu** [comment]
I've tried it with NextCloud 20.0.12 in a VM.
- Installed Music 1.3.1
- In the Settings, there is an "Ampache and Subsonic" section. Copied the url there into Ultrasonic as Server Address
- Clicked "Generate API password" in Nextcloud Music settings. It will print a username and an API password
- In Ultrasonic, entered the username and the password
- In Ultrasonic, enabled "self-signed certificate" because I have no https cert - you may not need it
- In Ultrasonic, enabled "force plain password authentication"
- Clicked Test Connection, the connection was OK with some missing features
- Clicked Save, selected server, and I can access my Music collection.

Please try these steps, and if the problem persists, provide some additional error details from Ultrasonic or Nextcloud Music logs, as it seems this should work out of the box.

**Comment by zoenglinghou** [comment]
@nitehu thank you for testing it out! I ended up enabling "force plain password authentication" and it works. It might have to do with the server, as I recently upgraded it to v1.3.1.

**Comment by rarealphacat** [comment]
> @nitehu thank you for testing it out! I ended up enabling "force plain password authentication" and it works. It might have to do with the server, as I recently upgraded it to v1.3.1.

Same setup as @zoenglinghou , Nextcloud server and works again after enabling force plain password authentication.

**Comment by moviuro** [comment]
@nitehu 's solution should probably be written somewhere (wiki?). I didn't punch in the "Save" button when I edited the config...

**Comment by nitehu** [comment]
You're right, this seems to be a common problem with many servers.
I'll add a wiki page and probably a FAQ too, because things like this are piling up...

**Comment by nitehu** [comment]
I've created a [FAQ](https://github.com/ultrasonic/ultrasonic/wiki/FAQ) with a question which describes this problem and the solution in details.
