### ISSUE TITLE
Better handling of podcasts

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#45]
Current implementation problems:
* doesn't mark podcast as played on the server
* filter out not yet downloaded podcasts

May add more later...

**Comment by solarchemist** [comment]
If I may add on OP's list:
Having used DSub, Subsonic and now Ultrasonic with my Subsonic/Libresonic/Airsonic servers, I would like the client to include a simple **chronological view of the latest added/aired episodes** from all podcasts on the server. DSub has something approaching this, but it only shows the latest handful of episodes which is an annoying and unnecessary cap.
If someone else would also like this, or if you know how to implement it, I would love to hear it.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
