### ISSUE TITLE
Rewriting app in kotlin

### ISSUE THREAD

**Issue by Tapchicoma** [ultrasonic/ultrasonic#5]
Hi @ogarcia.

What to do you think if I will start slowly rewriting this project using [kotlin](http://kotlinlang.org/) language?

**Comment by ogarcia** [comment]
Is a great idea. I cannot help you very much because I not have knowledge about kotlin and no much time for learn, but I can help you with testing and CI.

If you wish can open a new project in GitHub and add me as collaborator, we can make the work in this repository in other branch, but I think that is better that you lead the project.

**Comment by ogarcia** [comment]
BTW, @Tapchicoma  if you need have a collaborator in this project tell me 😉

**Comment by Tapchicoma** [comment]
I'd prefere to work on this repository and continue making releases of this app under current name and playstore id.

Actually I've already started rewriting Subsonic API client in kotlin. This is because app uses deprecated `org.apache.http` client and it is one the main blockers of further updating android support libs/target api.

IHMO better is to create a develop branch, where all new development will continue. At some point we can merge it into master and make a new app release.

**Comment by ogarcia** [comment]
Ok. I create a new develop orphan branch and add you as collaborator.

IMHO is better that the develop branch be orphan because if is a new rewrite and the history does not contribute too much.

When we can merge the new develop in master and make a new version (I think that v2.0 :wink:), we can rename the current master to OLD or simply upload it to some history and discard it. In the meantime if we need write some patch to current master we can use temp branches.

What do you think?

**Comment by Tapchicoma** [comment]
Ok, let's go with this approach.

**Comment by Tapchicoma** [comment]
Thinking about it again I am more considering merging master into develop branch.

The reasons for it:
- kotlin has good interop with java, usually there is no any problems
- developing app from scratch means that at some point we need to release it, but it also means that this app release has to have all current app functionality
- usually doing small changes and release them is much easier, then writing until some distant point in the feature
- we don't loose any other contributions
- continuous updates to the app

**Comment by ogarcia** [comment]
Ok. I'm thinking in a orphan branch to start with a new and pristine work environment, but start from current master is a good approach too.

I delete the orphan develop branch. When you have new changes can upload directly to a new develop branch without problem.

**Comment by Tapchicoma** [comment]
Closing this. Now we should create more specific issues.
