### ISSUE TITLE
Feature Request: filter random by server folder

### ISSUE THREAD

**Issue by johann1525** [ultrasonic/ultrasonic#521]
## Problem description

I'm running a big music library (>50k Songs) and i created some folders on my server to differentiate between media "types". E.g. audio books and music. It would be really useful if i could filter the "Random" section by server folder. Like it is already possible in the Artist view.

Or alternatively the folder selector on the individual lists could be removed all together and replaced by a global selector. Maybe put it on the top in the left menu?

### Steps to reproduce

Just create 2 or more folders on your server and try to generate the random section just for one folder. 

## System information

 * **Ultrasonic version**: 2.21.0
 * **Android version**: Lineage OS 18.1, 2021-06-06
 * **Device info**: OnePlus 8 Pro

## Additional notes

The webgui on my Airsonic is already behaving like this. There is a global option to select the folder. Every view, for example random, recently added or genres, are filtered by this setting.

A multi select instead of a radio button would also be convenient. But i don't know if the Backend is capable of this.

**Comment by tzugen** [comment]
I really like the second idea. 

(global folder selector in sidebar)

**Comment by ogarcia** [comment]
@tzugen see #393

**Comment by johann1525** [comment]
> @tzugen see #393

Server Selector != Folder Selector

**Comment by ogarcia** [comment]
> Server Selector != Folder Selector

Is an all-in-one / dependency feature

**Comment by johann1525** [comment]
> > Server Selector != Folder Selector
> 
> Is an all-in-one / dependency feature

all-in-one would be even better. 👍 i like it

**Comment by Bomfunk** [comment]
+1
A global folder selector would be great, so we can hide music in other folders.

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
