### ISSUE TITLE
Feature Request: play top songs / start radio

### ISSUE THREAD

**Issue by johann1525** [ultrasonic/ultrasonic#527]
## Problem description

I'd love to see the possibility to have the "Start Radio / Play Top Songs" feature in the app. Airsonic has it in the webgui in the artists info box. But i really don't know if this is part of the spec or a Airsonic thing. So maybe this is just not possible with the app.

## System information

 * **Ultrasonic version**: 2.21.0
 * **Android version**: Lineage OS 18.1, 2021-06-06
 * **Device info**: OnePlus 8 Pro

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
