### ISSUE TITLE
New image loader must be improved

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#531]
The new image uploader always re-downloads the images in all lists, these must be stored on the device and should only be reloaded if the user requests a list refresh. This is worse in artist's list where images are reloaded again and again in a simple scroll.

In the other hand, the album covers have the red/green triange in upper left corner (I think that we can remove it).

IMHO, if we want to do a new release must fix this issue or revert #514

**Comment by tzugen** [comment]
The artists covers don't show the triangle because they have the rounded corners applied, and this cuts off the triangle.
The images are stored in memory (as it was before with the Legacy method "addImageToCache"). 
The difference is that the Legacy loader didn't have a limit on the cache size and Picasso has.
So if you scroll for a while in the ArtistList, then the cache will be full, it Picasso will delete the first images again.

We can probably increase the cache limit.
Then the behaviour should be the same.

**Comment by tzugen** [comment]
On disk caching was only used before when users download songs, and this is the same now.

**Comment by tzugen** [comment]
Right now Picasso uses for the RAM cache 15% the available application RAM.
What do you think, how large should we make it?

**Comment by ogarcia** [comment]
And enable disk cache with a user setting (Image cache) in same way that music cache? Enabled by default with 100MB (for example).

Other option is leave to user select memory cache (with percent selector) or disk cache. But maybe it is too complex to implement. What do you think?

**Comment by tzugen** [comment]
I think it is better to have good defaults instead of a new preference.

22.06.2021 14:16:47 Óscar García Amor ***@***.***>:

**Comment by tzugen** [comment]
I have added a PR which increases the cache size from 14% to 25% of available Ram.
Adding a disk cache for all covers and not just for the offline cover is more complex,
because we want to keep the offline covers, while any random cover would be ok to delete when the disk cache is full.
So we would need actually two disk caches, one more temporary and one more permanent.

It is probably due to this complication that it was also not implemented in the Legacy loader. 
I think it will be possible, but would prefer to do it some later time, because it is not a regression from before..
