### ISSUE TITLE
Playlist should scroll to current track and have colors for past/current/next songs

### ISSUE THREAD

**Issue by moviuro** [ultrasonic/ultrasonic#547]
## Problem description

When playing a playlist, in the "Playlist" tab, I wish to quickly identify where I'm at. ATM, there is only a standard color "Play" icon next to the title of the current song

### Steps to reproduce

Launch a playlist, jump to the ~20th track.

Tap the playlist button (top right, next to the star).

### Current behavior

* The first tracks of the playlist are displayed
* All tracks have the same color scheme

### Expected behavior

* The playlist view should scroll so that the current track is in the middle of the screen (or, at least: is in view)
* Past tracks could be slightly grayed out (not necessary)
* The current track should be in ~bright or recognizable colors

## System information

 * **Ultrasonic version**: *2.22.0*
 * **Android version**: *S beta 3*
 * **Device info**: *Google Pixel 4a 5G*

## Other ideas

* Background color depends on current track position
![image](https://user-images.githubusercontent.com/6882978/126228925-47119636-7489-4f54-985b-76c68cdeba94.png)

**Comment by nitehu** [comment]
These are great ideas. 
The "scroll to current song" feature is already in Ultrasonic, just a bit buggy (as I remember there is an issue in github for this to be fixed already). As a temporary workaround, on the Now Playing screen if you click the playlist icon, at first it will jump to the start of the list. Click once more, and you're back with the album cover. Click the third time, and the playlist will appear with the current song. Weird, huh...

**Comment by moviuro** [comment]
> if you click the playlist icon, at first it will jump to the start of the list. Click once more, and you're back with the album cover. Click the third time, and the playlist will appear with the current song. Weird, huh...

Yes, indeed... i didn't even know it was there :open_mouth:

I would find it more intuitive to directly have the playlist button jump to the current track :wink:

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
