### ISSUE TITLE
Bluetooth not updating Now Playing information anymore

### ISSUE THREAD

**Issue by fexofenadine** [ultrasonic/ultrasonic#581]
## Problem description

The latest version does not update the currently playing Artist/Track after the first track is ended or skipped

### Steps to reproduce

Connect to bluetooth device that supports text, allow first track to finish, or skip to next track

## System information

 * **Ultrasonic version**: 2.23
 * **Android version**: 10
 * **Device info**: Samsung S9+

## Additional notes

Version 2.20 doesn't have the issue, nor do earlier versions. I have not checked 2.20 < n < 2.23, so a commit in that range could be responsible

Thank you!

**Comment by tzugen** [comment]
Thanks for reporting.
@nitehu is this the ad2p stuff?

**Comment by fexofenadine** [comment]
Ok to further narrow it down, 2.22 does not have the issue but 2.23 does. Hope this helps

**Comment by nitehu** [comment]
> @nitehu is this the ad2p stuff?

Yes I think it is. Maybe I successfully "optimized" it out with the Android Auto changes... 
I'll check and fix it.

**Comment by nitehu** [comment]
So yesterday I played with this a bit, and using a Sony headset with AVRCP 1.4 the tracks are displayed and updating correctly, this doesn't seem to be a trivial fix...
Also I've found a ton of similar problems with music apps [on google](https://www.google.com/search?q=android+bluetooth+track+info+not+updating&oq=android+bluetooth+track+info+not+updating&aqs=edge..69i57.41199j0j1&sourceid=chrome&ie=UTF-8), and the problem seems to be related to Android Auto somehow.

@fexofenadine did you find this issue with a car headunit, or is it related to Android Auto in any way for you (is it connected, your car supports it)?
[Some say that](https://www.toyotanation.com/threads/song-info-not-updating-over-bluetooth.1666904/) degrading the AVRCP version to 1.3 on the phone (and restarting it) fixes the problem, could you check this?

Meanwhile I'll check it in my car which have an older headunit and see if I can reproduce the problem.
So investigation is in progress, but I'm clueless for now and any tips are welcome.

**Comment by fexofenadine** [comment]
Hey hey, yes it's on a Sony car head unit with no Android Auto

I've just tested AVRCP 1.3, 1.4 (the default), 1.5 and 1.6, with the same results as before

**Comment by nitehu** [comment]
Unfortunately this works fine in my car, and I have no other bluetooth devices with a display, so I can't reproduce this.
I can only guess this has something to do with the MediaSession handling because that is the only related part which changed from 2.22 to 2.23...

@fexofenadine if I build and post a debug .apk with some changes reverted and trying a few things out, would you test it to see if anything improves? Maybe we can find which part of the code does this...

**Comment by fexofenadine** [comment]
Absolutely, no problem

Thanks for looking at this, I've mostly been using 2.22 since I first noticed the issue

**Comment by nitehu** [comment]
[ultrasonic-debug.zip](https://github.com/ultrasonic/ultrasonic/files/7178928/ultrasonic-debug.zip)

The attached (zipped) .apk is the newest Ultrasonic with one modification: the updateMediaSession has been changed back to the 2.22 version. In 2.23 the play queue handling was added, which is necessary for Android Auto, but is not supported in AVRCP 1.3 (only in 1.4).   

Let's see if this is the change that causes the problem.

**Comment by fexofenadine** [comment]
That seems to have resolved the problem, yes!

**Comment by fexofenadine** [comment]
Hey so I can't get Package Manager to install that apk, I keep getting "App Not Installed". I've tried uninstalling 2.22 first but it doesn't seem to help - I can install third party apps usually (my usual Ultrasonic install method is GitHub APKs)

Am I doing something wrong?

**Comment by fexofenadine** [comment]
Ok I can't install it on my other android devices either.  But something I discovered while doing that: 2.23.1 on an old Galaxy Tab A (same headunit) does not have the issue. So maybe it's something specific to my phone hardware?

Please let me know if I can do anything to help

**Comment by nitehu** [comment]
[ultrasonic-release.zip](https://github.com/ultrasonic/ultrasonic/files/7183160/ultrasonic-release.zip)
Sorry could you please try this one? I didn't sign the previous.

My current guess is that the problem is related to the bluetooth firmware on your phone and also on your headunit, so if you change the phone or the headunit the issue may disappear.

**Comment by fexofenadine** [comment]
Okay yes that works great, track info diplaying correctly now

It doesn't seem to show the progress of the track(s) anymore but that is certainly a minor issue

**Comment by nitehu** [comment]
Thank you for testing!
Yes, track progress was added in 2.23, but I reverted all the information to the 2.22 level.

Would you please try this version too? In this I removed only the now playing queue.
[ultrasonic-release.zip](https://github.com/ultrasonic/ultrasonic/files/7184435/ultrasonic-release.zip)

If this still works correctly, we can add a compatibility switch for AVRCP 1.3 to the settings. This way it will work for everybody (I hope :)

**Comment by fexofenadine** [comment]
Yes that's also working, the progress is back too :)

**Comment by nitehu** [comment]
Thank you very much for your help, I'll add the compatibility switch in one of the upcoming versions!

**Comment by fexofenadine** [comment]
Awesome, thanks mate!

**Comment by heinhuiz** [comment]
This issue is back for me since version 3.x.x. Currently I stay on 2.24.0, because none of the settings combinations seem to work for me. I have all Notifications options set and then they work fine.

**Comment by nitehu** [comment]
Ugh, thanks for reporting this... I don't think we've modified anything related, but I will keep an eye out. Currently my best guess is it has something to do with the new google api version...

**Comment by tzugen** [comment]
Yes, that's was my first thought as well. I can't remember that we touched any code there...

**Comment by tzugen** [comment]
Please check with #726

**Comment by fexofenadine** [comment]
Is there a compiled build I can test the changes on?

**Comment by tzugen** [comment]
Here you go:
https://github.com/ultrasonic/ultrasonic/releases/tag/4.0.0-beta

@fexofenadine

**Comment by fexofenadine** [comment]
Hi mate, I get "app not installed as package appears to be invalid" when I try to install, even if I uninstall the 3.x version first

**Comment by fexofenadine** [comment]
Ok the newest build installs fine after uninstalling the 3.x package

I'm happy to report that this has fixed the track info updating for me. 

On a side note, I did have some weird issues where tracks would stop playing after 10 seconds or so, and the progress indicator was being very strange (ticking back and forth from 0:00s to 0:01s until the track stopped). This seems to be resolved after rebooting my phone though, so might just be my end.

Anyhow, thanks for looking into and resolving this issue

**Comment by tzugen** [comment]
Thanks for the update!
If you see the weird issue again just let us know...

**Comment by tzugen** [comment]
Fixed #743
